### ISSUE TITLE
Gossip driver for this repo

### ISSUE THREAD

**Issue by mattcollier** [anuragpeshne/dsplotty#1]
Hello, I became aware of this project based on a youtube video: https://www.youtube.com/watch?v=8hV5Z3F5fTU

I can see that this project functions with a basic command line: 
```
echo '<plotty: draw, 10>' | node index.js
```

Is the code that was used to generate the data set for the youtube video and the example animation available somewhere?

**Comment by anuragpeshne** [comment]
The code that generated the gossip protocol animation is private. I have included a sample script which might help in understanding how to use this project: [sample.sh](https://github.com/anuragpeshne/dsplotty/blob/master/sample.sh)
